### PR TITLE
added LED status of motor board to readme

### PR DESCRIPTION
**Pull request by ferdinand-wood**

### CODE REVIEW

**Review by fgrimminger — APPROVED** [review]
Good idea. Thanks.

**Comment by jviereck** [comment]
> RED LED: Turn on if there is an error

Is that true? If I turn on solo12, it will first blink red, then I connect which makes the connection go to green.

@ferdinand-wood , what do you think?

**Comment by thomasfla** [comment]
Hi, This is the motor driver led description, not master board.

Le ven. 26 févr. 2021 à 19:59, Julian Viereck <notifications@github.com> a
écrit :

**Comment by jviereck** [comment]
Makes total sense, please ignore my comment then.

**Pull request merged**
